### ISSUE TITLE
cloud I create and update at once using same csv?

### ISSUE THREAD

**Issue by kshke** [onozaty/redmine-issue-loader#1]
Hi Onozay

This tools help me a lot! thank you. 
In addition, I want to ask a question. If i can create and update issue at once using same csv?  for example : I update existed issue in csv (No 17-22) and also add new issue (No 23) in csv. when i run the command java -jar redmine-issue-loader-2.0.0-all.jar config-update-with-issue_id.json  issues.csv . 
it return an error,
Processing start...
#22 is updated.
#21 is updated.
#20 is updated.
#19 is updated.
#18 is updated.
#17 is updated.
Exception in thread "main" java.lang.IllegalStateException: The target issue was not found. IssueId(id=23.

**Comment by onozaty** [comment]
Hi @kshke 

Currently, it is not possible to update and create with a single CSV file.
Create two types of configuration file and CSV file and execute each.

Thanks.

**Comment by kshke** [comment]
Hi @onozaty 
got it. thank you for your reply!
