### ISSUE TITLE
 field type can only be [ISSUE_ID, TRACKER_ID, PARENT_ISSUE_ID, STATUS_ID, CATEGORY_ID, PROJECT_ID, PRIORITY_ID, DESCRIPTION, SUBJECT, CUSTOM_FIELD]?

### ISSUE THREAD

**Issue by kshke** [onozaty/redmine-issue-loader#2]
Hi Onozaty

I want to export some new issue, the type include file such as Assignee,Target version,Start date..etc.
but when I run the command , it returns an error:
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.enjoyxstudy.redmine.issue.loader.input.FieldType` from String "assigned_to_id": value not one of declared Enum instance names: **[ISSUE_ID, TRACKER_ID, PARENT_ISSUE_ID, STATUS_ID, CATEGORY_ID, PROJECT_ID, PRIORITY_ID, DESCRIPTION, SUBJECT, CUSTOM_FIELD]**

Is field type can only be [ISSUE_ID, TRACKER_ID, PARENT_ISSUE_ID, STATUS_ID, CATEGORY_ID, PROJECT_ID, PRIORITY_ID, DESCRIPTION, SUBJECT, CUSTOM_FIELD]?

Thank in advance.
Amy

**Comment by onozaty** [comment]
Hi @kshke 

> Is field type can only be [ISSUE_ID, TRACKER_ID, PARENT_ISSUE_ID, STATUS_ID, CATEGORY_ID, PROJECT_ID, PRIORITY_ID, DESCRIPTION, SUBJECT, CUSTOM_FIELD]?
> 

Yes.

Can you tell me what you need because I want to consider adding field types?

**Comment by dlyjie** [comment]
Hi Onozaty,
Could you add all fields to convenience for everyone to choose?  Looking forward for your reply!

**Comment by onozaty** [comment]
Hi @dlyjie 

I want to add what I think is necessary, not everything.
Can you tell me what you need fields?

**Comment by onozaty** [comment]
Hi @dlyjie @kshke 

Added support for other fields!!
Released as version 2.1.0.

* https://github.com/onozaty/redmine-issue-loader/releases/tag/v2.1.0
