### ISSUE TITLE
Does this tool support Basic Authentication ?

### ISSUE THREAD

**Issue by ryoji-takeuchi** [onozaty/redmine-issue-loader#5]
Our Redmine is running on server which is implemented Basic Authentication.
Does this tool support Basic Authentication ?

**Comment by onozaty** [comment]
Currently not supported.
I will implement from now on. Please wait a moment.

**Comment by onozaty** [comment]
Supported at v2.2.0.
* https://github.com/onozaty/redmine-issue-loader/releases/tag/v2.2.0
